spring:
  application:
    name: order
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wavaya/config-repo
          username: wavaya
          password: wayhua888
  #          basedir:
  bus:
      #Workaround for defect in https://github.com/spring-cloud/spring-cloud-bus/issues/124
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}
  rabbitmq:
    host: 192.168.31.59
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.59/sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8036
girl:
  name: danny
  age: 18
env:
   dev
