spring:
  application:
    name: order
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wavaya/config-repo
          username: wavaya
          password: wayhua888
  #          basedir:
  rabbitmq:
    host: 192.168.31.226
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.226/sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8036
girl:
  name: danny
  age: 57
env:
   dev
