eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  level:
    com:
      wayhua:
        order: debug
server:
  port: 8070
spring:
  application:
    name: order
env:
   dev
